### ISSUE TITLE
HyperLinks

### ISSUE THREAD

**Issue by itsteja17** [alan412/LearnJavaForFTC#12]
May 7, 2020

General

Since this is going to be released as a PDF, adding hyperlinks where you mention “we will be discussing this more in …” and the TOC would be helpful.

**Comment by E-Terry** [comment]
I’m not sure about the “we will mention this more, but the table of contents *does* have hyperlinks, they just don’t seem to work in the browser. They worked for me when I downloaded the file but not in the browser on GitHub.

**Comment by alan412** [comment]
Agree with @E-Terry - The problem is the PDF reader in the browser.   If you download the PDF, the links should work.
