### ISSUE TITLE
4.3 

### ISSUE THREAD

**Issue by Joshua-Smith-42** [alan412/LearnJavaForFTC#13]
May 9th 2020

4.3 comanations

I know in python there is a logic operator that is **exclusive or** does that exist in java???
If it does it wasn't on the chart

**Comment by itsteja17** [comment]
Hi Joshua, 

The logic operator exclusive or does exist in Java. 

Operator: ^
Example: A ^ B 
Meaning: return TRUE if condition A and B are different, otherwise return FALSE

**Comment by alan412** [comment]
Technically, the XOR operator (^) is a bitwise operator and not a logical one in Java.  I added it for completeness because it can be used like that when both arguments are boolean.  However, if they are integers then it will operate on each bit in the data which may give an unexpected result.
