### ISSUE TITLE
Confusion about descriptive vs. literals    for example true and false.

### ISSUE THREAD

**Issue by alanbee55** [alan412/LearnJavaForFTC#20]
# Date on version you are commenting on
May 23, 2020

# Section you are commenting on
2.1

# Comments
you describe a boolean being true vs. false.  It looks like you tried a font change to make the point about the literal, but it isn't explained.  Have you thought about something a little more distinctive?

**Comment by alan412** [comment]
I tried putting something in the beginning (version not up yet) about what the font change means but it isn't very good.
