### ISSUE TITLE
Recommendation for if/then code blocks

### ISSUE THREAD

**Issue by alanbee55** [alan412/LearnJavaForFTC#24]
# Date on version you are commenting on
May 23, 2020

# Section you are commenting on
example - 4.1

# Comments
It might emphasize the point for your strong recommendation  by pointing out that subtle errors can be introduced by carelessly adding lines to single statements.

**Comment by alan412** [comment]
good point.  I'll write some bad code to show it

**Comment by alanbee55** [comment]
That's all it will take
