### ISSUE TITLE
Inheritance Examples Breakdown

### ISSUE THREAD

**Issue by E-Terry** [alan412/LearnJavaForFTC#3]
# Date on version you are commenting on
May 7, 2020

# Section you are commenting on
So why in the world would you use this? - 14.2

# Comments
In the explanations of Listings 14.4 and 14.7 the boxes to highlight the code you are explaining are either empty or are showing what I assume are the wrong lines, as they do not pertain to the explanation after them.

After Listing 14.4, the first box is correct but the second is empty. I assume you meant to highlight line 16?

and after listing 14.7, you have 1 empty box and then three highlighting gyro code that doesn't pertain to the explanation. I am going to guess that you meant to highlight line 87, and then in the next box 88, and then 89 and 90 in the next box, and then 91 in the last.

**Comment by alan412** [comment]
Great catch.   As you probably guessed, I am using some macros to automatically pull in the code listings and something got way off in those two files.   Thanks!!!   I have updated with a new version that fixes it.

**Comment by alan412** [comment]
Eli - are you on an FTC team so I can put it in the credits?

**Comment by E-Terry** [comment]
Sorry. Did not see this until now. Yes, I am on a team. I am a part of the
RoboKnights.
