### ISSUE TITLE
Method sentence

### ISSUE THREAD

**Issue by Ellie416** [alan412/LearnJavaForFTC#34]
# Date on version you are commenting on
June 7, 2020

# Section you are commenting on
1.2.1

# Comments
In the methods section, the first sentence reads a bit awkwardly. I’d maybe say something like “A method is a group of code within a class. Methods are the smallest groups of code that can be executed.”

**Comment by alan412** [comment]
Thank you for this and the other comments.  If you give me your name and FTC #, then I'll be happy to put you in the Credits...

**Comment by Ellie416** [comment]
Cool! This is Ellie Larsen from the roboknights (8569)
