### ISSUE TITLE
Package explanation

### ISSUE THREAD

**Issue by Ellie416** [alan412/LearnJavaForFTC#35]
# Date on version you are commenting on
June 7, 2020

# Section you are commenting on
1.2.1

# Comments
I don’t really understand the explanation of a package; it’s a “directory” but what does it actually do? Also, I assume there’s a reason you didn’t go into depth on this but it’s unclear what’s meant by “Files in the same package have special privileges with each other.”

**Comment by alan412** [comment]
Is this more clear?

**package** A directory in JAVA. It is where the code is located. Files in the same package have special privileges with each other. We’ll talk about this in section 5.3. And yes, a package can have packages within it.

**Comment by Ellie416** [comment]
Yeah, that makes sense; it’s useful that there’s a reference to where you go more in depth on it.
