### ISSUE TITLE
String definition

### ISSUE THREAD

**Issue by Ellie416** [alan412/LearnJavaForFTC#37]
# Date on version you are commenting on
June 7, 2020

# Section you are commenting on
1.2.4

# Comments
In the last paragraph of page 5 you mention a string, and I think it might be helpful just to add something like “, or group of characters,” after “a string” just so that complete beginners don’t get caught off guard by new vocab before you go in depth into what strings are later on.

**Comment by alan412** [comment]
good catch.  I have updated the text
