### ISSUE TITLE
Clarity

### ISSUE THREAD

**Issue by burtonboucher** [alan412/LearnJavaForFTC#42]
# Date on version you are commenting on
June 10, 2020

# Section you are commenting on
5.1

# Comments
“ This is a little strange because even though initDone gets updated in init(), nothing sends it to the driver station until loop() gets called for the first time.”  I lost context from prior sentence. I guess I was looking for a connection backward to answer “this is a little strange”. Maybe just describe The steps how the value is set to controller. 

So far this is very good and helpful!

**Comment by alan412** [comment]
good comment.  I'll make the change.
