### ISSUE TITLE
New Class Dialog

### ISSUE THREAD

**Issue by burtonboucher** [alan412/LearnJavaForFTC#47]
# Date on version you are commenting on
July 27, 2020

# Section you are commenting on
1.3

# Comments
When creating a new Java Class I do not get the full dialog. Only can enter name. No drop downs for Superclass, Interface, Package,.... I tried to install default Android template from here: https://developer.android.com/studio/write/create-java-class#class
This provides text fields but not drop downs. Is this template added during install and or Gradle?

**Comment by alan412** [comment]
Arrrgghh, Android Studio changed the dialog with Android Studio 4.   Thanks for letting me know.   Let me see how to do this.

**Comment by alan412** [comment]
I am obviously not the only one unhappy: https://stackoverflow.com/questions/62339552/android-studio-intellij-new-java-class-wizard

**Comment by alan412** [comment]
For anyone else looking here:
  - Steps: 
    * Just type in the class name
    * After the file is created add the "extends OpMode" to match what the listing looks like in section 1.3

**Comment by burtonboucher** [comment]
> I am obviously not the only one unhappy: https://stackoverflow.com/questions/62339552/android-studio-intellij-new-java-class-wizard

This is what I tried. It does provide the dialog mentioned but it’s not the one with drop down lists. Not knowing the IDE it sounds to me like template needs a macro to populate Superclass, Interface,...
