### ISSUE TITLE
Decrement Operator

### ISSUE THREAD

**Issue by stratosonic** [alan412/LearnJavaForFTC#54]
# Date on version you are commenting on
May 4, 2022

# Section you are commenting on
3.2 Other assignment operators

# Comments
In the table of assignment operators, the decrement operator has a typo (x- vs x--).

**Comment by alan412** [comment]
Thank you! If you give me your name (and FTC team you are associated with), then I'll add you to the credits!!

**Comment by stratosonic** [comment]
Glad to help, the book has been a great resource for our team!

Jason
FTC #18291 - Mech Warriors

**Comment by alan412** [comment]
:-).  You are in the credits now with the newest version uploaded today!
