### ISSUE TITLE
Update to IMU

### ISSUE THREAD

**Issue by AAbshagen76** [alan412/LearnJavaForFTC#56]
# Date on version you are commenting on
Feb 3, 2023

# Section you are commenting on
11

# Comments
Any chance you will be updating the Gyro section to include the changes to the BHI260AP IMU that is included in the newer Control Hubs?  There are some differences and more options available with the newer chip.  Currently working through those changes as I believe it may be affecting the mecanum drive code that is included in section 20.2.3.

Maybe this is by design.  But the field relative drive code is having the robot turn around instead of just operating backwards as I would have expected it would do.

**Comment by alan412** [comment]
I will.  I don't have a newer control hub to test on but one is supposed to be on its way.   Can you send me a video of what your robot is doing with the field relative drive code?  It shouldn't be causing the robot to turn around.

**Comment by alan412** [comment]
I found and fixed the problem using the beta8397 simulator.   It isn't due to the new imu, there was a bug in the Mecanum Drive class.    I put the correct code in as an issue on your repo.   (I apologize as this was issue #55 where the text in the book was wrong even though the code was correct.)
