### ISSUE TITLE
Amazon Print

### ISSUE THREAD

**Issue by rachtw** [alan412/LearnJavaForFTC#59]
# Date on version you are commenting on
Aug 11, 2020

# Section you are commenting on
3.2

# Comments
Hi, I am interested in using your book. Is the Amazon link the latest version? Or how different is that compared to the latest one? Thank you!

**Comment by alan412** [comment]
The Amazon version is up to date right now with the version here.  Typically I upload them at the same time, and Amazon normally approves the updates within 24 hours.
