### ISSUE TITLE
Include methods

### ISSUE THREAD

**Issue by Jeff-F10** [alan412/LearnJavaForFTC#64]
# Date on version you are commenting on
Oct 4, 2023

# Section you are commenting on

# Comments
I would like to write separate methods (subroutines) and then include them into the program build without cutting and pasting.  How can I do this in Android Studio

thanks
Jeff Friedhoffer
Jafried@ieee.org

**Comment by alan412** [comment]
To create a separate method in Java, you just declare the method inside the
class.    This is described in section 5.2

Hope this helps!!

--Alan
