### ISSUE TITLE
3d-Printed Programming Board companion to this book

### ISSUE THREAD

**Issue by anpark1234** [alan412/LearnJavaForFTC#70]
Hi! This is an awesome book - thanks so much for publishing this. I wanted to share with you a programming board I designed and the team I mentor uses along with this book. We put it on thingiverse so others can print it out and use it too.

https://www.thingiverse.com/thing:6864893

- Coach Anthony with Team #26037 Cyber Tigers.

**Comment by alan412** [comment]
That is way cool!   I'll mention it in a future edition of the book.
